const rows = [
  ["r01","Pausa de olhos fechados","Descanse os olhos por dois minutos.",["rest","selfcare","quick"],["tired","anxious","neutral"],2,["all"],"low","/lar"],
  ["r02","Janela sem pressa","Observe a luz pela janela por cinco minutos.",["rest","outdoors"],["tired","calm","sad"],5,["morning","afternoon"],"low","/lar"],
  ["r03","Silêncio confortável","Fique alguns minutos sem notificações.",["rest","selfcare"],["tired","irritated","confused"],10,["all"],"low","/lar"],
  ["r04","Descanso para as mãos","Solte celular e teclado por dois minutos.",["rest","selfcare","quick"],["tired","anxious"],2,["all"],"low","/lar"],
  ["r05","Intervalo com água","Beba água devagar e respire naturalmente.",["rest","selfcare","quick"],["neutral","tired","anxious"],5,["all"],"low","/lar"],
  ["r06","Cantinho tranquilo","Ajuste um lugar confortável para uma pausa.",["rest","organization"],["tired","sad","irritated"],10,["evening","night"],"low","/lar"],
  ["r07","Pausa entre tarefas","Termine uma coisa e espere antes da próxima.",["rest","quick"],["tired","unmotivated","confused"],5,["afternoon","evening"],"low","/lar"],
  ["c01","Rosto refrescado","Lave o rosto com calma.",["selfcare","quick"],["tired","sad","neutral"],5,["all"],"low","/lar"],
  ["c02","Alongar os ombros","Faça movimentos suaves, sem forçar.",["selfcare","movement","quick"],["tired","anxious"],5,["all"],"low","/lar"],
  ["c03","Preparar um lanche","Escolha algo simples que você goste.",["selfcare","organization"],["neutral","tired","unmotivated"],15,["all"],"low","/lar"],
  ["c04","Cuidar do ambiente","Abra a janela ou ajuste a iluminação.",["selfcare","organization","starting"],["calm","confused","neutral"],5,["morning","afternoon"],"low","/lar"],
  ["c05","Banho sem correria","Reserve um banho tranquilo quando puder.",["selfcare","rest"],["tired","sad","irritated"],30,["evening","night"],"low","/lar"],
  ["c06","Gentileza consigo","Escreva uma frase acolhedora para você.",["selfcare","diary"],["sad","anxious","unmotivated"],5,["all"],"low","/diario"],
  ["c07","Respiração natural","Perceba três respirações sem tentar mudá-las.",["selfcare","quick","rest"],["anxious","irritated","confused"],2,["all"],"low","/lar"],
  ["o01","Uma gaveta apenas","Organize só uma gaveta ou prateleira.",["organization","quick"],["neutral","excited","confused"],10,["all"],"medium","/lar"],
  ["o02","Mesa respirando","Retire três coisas que não precisam ficar na mesa.",["organization","quick"],["confused","unmotivated"],5,["morning","afternoon"],"low","/lar"],
  ["o03","Próximo compromisso","Confira somente o próximo evento.",["organization","calendar","quick"],["anxious","neutral"],2,["all"],"low","/calendario"],
  ["o04","Lista mínima","Escolha uma prioridade e duas opcionais.",["organization","goals","starting"],["confused","anxious","unmotivated"],5,["morning"],"low","/metas"],
  ["o05","Bolsa pronta","Separe o necessário para a próxima saída.",["organization","closing"],["neutral","calm"],10,["evening","night"],"low","/lar"],
  ["o06","Arquivos em ordem","Organize uma pequena pasta digital.",["organization","quick"],["neutral","excited"],15,["afternoon","evening"],"medium","/lar"],
  ["o07","Calendário tranquilo","Veja a semana e ajuste o que estiver apertado.",["organization","calendar","rest"],["anxious","confused"],15,["weekend","evening"],"low","/calendario"],
  ["a01","Rabisco livre","Desenhe sem buscar um resultado.",["creativity","quick"],["excited","calm","neutral"],5,["all"],"low","/lar"],
  ["a02","Foto de uma cor","Registre algo com uma cor que chamou atenção.",["creativity","outdoors"],["happy","excited","calm"],10,["morning","afternoon"],"low","/lar"],
  ["a03","Mini história","Escreva uma história em cinco frases.",["creativity","diary"],["excited","confused","neutral"],10,["all"],"medium","/diario"],
  ["a04","Nova combinação","Monte uma roupa ou objeto de um jeito diferente.",["creativity","organization"],["excited","happy"],15,["morning","afternoon"],"medium","/lar"],
  ["a05","Colagem de ideias","Junte palavras que combinam com seu momento.",["creativity","diary"],["confused","sad","calm"],15,["all"],"low","/diario"],
  ["a06","Som do ambiente","Perceba sons próximos e crie um ritmo.",["creativity","music","quick"],["calm","excited","neutral"],5,["all"],"low","/lar"],
  ["a07","Receita adaptada","Mude um detalhe simples de uma receita.",["creativity","selfcare"],["happy","excited","neutral"],30,["weekend","evening"],"medium","/lar"],
  ["m01","Caminhada pelo quarteirão","Saia por alguns minutos, se o lugar for seguro.",["movement","outdoors"],["excited","irritated","neutral"],15,["morning","afternoon"],"medium","/lar"],
  ["m02","Movimento sentado","Gire pés e ombros de forma confortável.",["movement","selfcare","quick"],["tired","anxious"],5,["all"],"low","/lar"],
  ["m03","Uma música em pé","Movimente-se durante uma faixa curta.",["movement","music"],["happy","excited","unmotivated"],5,["all"],"medium","/lar"],
  ["m04","Escada tranquila","Suba alguns degraus no seu ritmo.",["movement","quick"],["neutral","excited"],5,["morning","afternoon"],"medium","/lar"],
  ["m05","Alongamento de manhã","Acorde o corpo com movimentos leves.",["movement","starting","selfcare"],["neutral","calm","tired"],10,["morning"],"low","/lar"],
  ["m06","Passeio sem meta","Caminhe sem contar distância ou desempenho.",["movement","outdoors","rest"],["anxious","sad","irritated"],30,["weekend","afternoon"],"low","/lar"],
  ["m07","Dança de uma faixa","Escolha uma música e dance como quiser.",["movement","music","creativity"],["happy","excited"],5,["all"],"high","/lar"],
  ["e01","Céu por cinco minutos","Observe o céu de um local seguro.",["outdoors","rest","quick"],["calm","sad","neutral"],5,["morning","afternoon","evening"],"low","/lar"],
  ["e02","Volta na rua","Faça uma pequena volta sem medir desempenho.",["outdoors","movement"],["neutral","irritated","excited"],15,["morning","afternoon"],"medium","/lar"],
  ["e03","Planta por perto","Observe uma planta e seus pequenos detalhes.",["outdoors","selfcare","quick"],["anxious","calm","sad"],5,["all"],"low","/lar"],
  ["e04","Luz da manhã","Passe alguns minutos em um lugar iluminado.",["outdoors","starting"],["tired","neutral","calm"],10,["morning"],"low","/lar"],
  ["e05","Banco tranquilo","Sente-se ao ar livre sem precisar fazer nada.",["outdoors","rest"],["tired","sad","anxious"],15,["afternoon","weekend"],"low","/lar"],
  ["e06","Caminho diferente","Escolha uma rota segura um pouco diferente.",["outdoors","movement","creativity"],["excited","happy","neutral"],30,["weekend","afternoon"],"medium","/lar"],
  ["e07","Ouvir a chuva","Se estiver chovendo, escute de um lugar protegido.",["outdoors","music","rest"],["calm","sad","tired"],10,["all"],"low","/lar"],
  ["e08","Fim de tarde","Acompanhe a mudança da luz por alguns minutos.",["outdoors","closing","rest"],["calm","neutral","confused"],15,["evening"],"low","/lar"],
  ["s01","Mensagem breve","Envie um oi para alguém de confiança.",["social","quick"],["sad","neutral","happy"],2,["all"],"low","/lar"],
  ["s02","Áudio carinhoso","Grave uma mensagem curta para alguém próximo.",["social","creativity"],["happy","excited","neutral"],5,["all"],"low","/lar"],
  ["s03","Café compartilhado","Convide alguém para uma pausa sem pressa.",["social","rest"],["neutral","sad","calm"],30,["weekend","afternoon"],"low","/lar"],
  ["s04","Agradecimento simples","Diga a alguém algo que você aprecia.",["social","selfcare","quick"],["happy","calm","neutral"],5,["all"],"low","/lar"],
  ["s05","Pergunta sincera","Pergunte como alguém de confiança está.",["social","quick"],["neutral","sad"],5,["all"],"low","/lar"],
  ["s06","Plano leve","Combine uma atividade tranquila para outro dia.",["social","organization"],["excited","happy","neutral"],10,["evening","weekend"],"low","/calendario"],
  ["s07","Ajuda pequena","Ofereça uma ajuda que caiba no seu momento.",["social","selfcare"],["happy","excited","calm"],15,["all"],"medium","/lar"],
  ["s08","Presença sem conselho","Escute alguém sem precisar resolver nada.",["social","rest"],["calm","neutral","sad"],30,["all"],"low","/lar"],
  ["d01","Três coisas boas","Anote três detalhes agradáveis do dia.",["diary","quick"],["happy","calm","neutral"],5,["evening","night"],"low","/diario"],
  ["d02","Página sem filtro","Escreva livremente por dez minutos.",["diary","creativity"],["confused","sad","irritated"],10,["all"],"low","/diario"],
  ["d03","Uma frase basta","Registre somente uma frase sobre agora.",["diary","quick"],["tired","unmotivated","neutral"],2,["all"],"low","/diario"],
  ["d04","Carta para amanhã","Deixe uma mensagem curta para seu próximo dia.",["diary","closing"],["anxious","calm","confused"],5,["night"],"low","/diario"],
  ["d05","O que ajudou","Registre algo que tornou hoje um pouco mais leve.",["diary","selfcare"],["sad","tired","neutral"],5,["evening","night"],"low","/diario"],
  ["d06","Detalhe do lugar","Descreva o ambiente onde você está.",["diary","creativity"],["calm","confused","neutral"],10,["all"],"low","/diario"],
  ["d07","Pergunta do dia","Escreva uma pergunta que deseja guardar.",["diary","creativity"],["confused","excited","neutral"],5,["all"],"low","/diario"],
  ["d08","Lista de pequenas vitórias","Anote avanços sem transformar o dia em competição.",["diary","goals"],["happy","unmotivated","neutral"],10,["evening"],"low","/diario"],
  ["g01","Próximo passo mínimo","Escolha uma ação pequena para uma meta.",["goals","quick"],["unmotivated","confused","neutral"],5,["all"],"low","/metas"],
  ["g02","Rever uma meta","Leia uma meta sem obrigação de avançar.",["goals","rest"],["tired","anxious","neutral"],5,["evening"],"low","/metas"],
  ["g03","Celebrar um avanço","Reconheça algo que já caminhou.",["goals","diary"],["happy","calm","neutral"],5,["all"],"low","/metas"],
  ["g04","Prazo realista","Veja se um prazo ainda combina com sua rotina.",["goals","organization"],["anxious","confused"],10,["weekend","evening"],"low","/metas"],
  ["g05","Meta em dois minutos","Faça a menor parte possível de uma meta.",["goals","quick"],["unmotivated","tired"],2,["all"],"low","/metas"],
  ["g06","Uma etapa concluída","Escolha uma etapa que caiba neste momento.",["goals","organization"],["excited","neutral"],15,["morning","afternoon"],"medium","/metas"],
  ["g07","Pausar com intenção","Pause uma meta que não precisa ser prioridade agora.",["goals","rest","selfcare"],["tired","anxious"],10,["evening"],"low","/metas"],
  ["h01","Hábito mais simples","Conclua a versão mais leve de um hábito.",["habits","quick"],["tired","unmotivated","neutral"],5,["all"],"low","/habitos"],
  ["h02","Preparar o hábito","Deixe pronto o que facilitará o próximo registro.",["habits","organization"],["neutral","confused"],10,["evening"],"low","/habitos"],
  ["h03","Rever a frequência","Confira se um hábito ainda cabe na sua semana.",["habits","selfcare"],["tired","anxious","neutral"],10,["weekend"],"low","/habitos"],
  ["h04","Um registro hoje","Marque o hábito que você já realizou.",["habits","quick"],["happy","neutral","calm"],2,["all"],"low","/habitos"],
  ["h05","Hábito com música","Faça um hábito durante uma faixa tranquila.",["habits","music"],["unmotivated","happy"],5,["all"],"medium","/habitos"],
  ["h06","Começar sem terminar","Inicie um hábito por dois minutos e pare se quiser.",["habits","quick"],["unmotivated","tired"],2,["all"],"low","/habitos"],
  ["h07","Dia de descanso","Arquive ou adie sem culpa o que não cabe hoje.",["habits","rest"],["tired","sad","anxious"],5,["all"],"low","/habitos"],
  ["h08","Sequência com gentileza","Veja sua sequência como memória, não cobrança.",["habits","selfcare"],["neutral","calm","confused"],5,["evening"],"low","/habitos"],
  ["u01","Lo-fi por uma faixa","Escolha uma música ambiente e apenas escute.",["music","rest"],["tired","calm","neutral"],5,["all"],"low","/lar"],
  ["u02","Música para começar","Use uma faixa leve para acompanhar o início do dia.",["music","starting"],["neutral","happy","tired"],10,["morning"],"low","/lar"],
  ["u03","Som para organizar","Coloque uma faixa enquanto guarda poucas coisas.",["music","organization"],["unmotivated","neutral"],10,["afternoon","evening"],"low","/lar"],
  ["u04","Ouvir um favorito","Reencontre uma música salva por você.",["music","favorites"],["sad","calm","happy"],5,["all"],"low","/favoritos"],
  ["u05","Uma faixa sem tela","Ouça sem acompanhar notificações.",["music","rest"],["anxious","irritated","tired"],5,["all"],"low","/lar"],
  ["u06","Ritmo para caminhar","Escolha uma música para um passeio seguro.",["music","movement","outdoors"],["excited","happy","neutral"],15,["morning","afternoon"],"medium","/lar"],
  ["u07","Música de encerramento","Escolha um som tranquilo para terminar o dia.",["music","closing","rest"],["tired","calm","neutral"],10,["night"],"low","/lar"],
  ["u08","Descobrir detalhes","Ouça novamente e perceba um instrumento diferente.",["music","creativity"],["calm","excited","neutral"],5,["all"],"low","/lar"],
  ["f01","Episódio curto","Escolha uma série salva com episódio breve.",["screen","favorites","rest"],["tired","neutral"],30,["evening","night"],"low","/favoritos"],
  ["f02","Cena confortável","Reveja uma cena de algo que você gosta.",["screen","favorites","quick"],["sad","tired","calm"],10,["all"],"low","/favoritos"],
  ["f03","Comédia leve","Procure entre seus Favoritos algo marcado como divertido.",["screen","favorites"],["sad","neutral","happy"],30,["weekend","evening"],"low","/favoritos"],
  ["f04","Filme sem pressa","Reserve um horário futuro para um filme salvo.",["screen","calendar","organization"],["excited","happy","neutral"],10,["all"],"low","/calendario"],
  ["f05","Documentário curto","Escolha um tema que desperte curiosidade.",["screen","creativity"],["excited","confused","neutral"],30,["weekend"],"low","/favoritos"],
  ["f06","Assistir acompanhado","Convide alguém para ver algo leve.",["screen","social"],["happy","neutral","sad"],30,["weekend","evening"],"low","/favoritos"],
  ["f07","Uma recomendação sua","Revisite algo que você mesmo marcou como confortável.",["screen","favorites","selfcare"],["tired","sad","anxious"],30,["night"],"low","/favoritos"],
  ["f08","Escolher sem rolar muito","Defina uma opção antes de abrir o catálogo.",["screen","organization","quick"],["confused","tired"],5,["evening"],"low","/favoritos"],
  ["l01","Duas páginas","Leia apenas duas páginas de um livro salvo.",["books","quick","favorites"],["tired","unmotivated","neutral"],5,["all"],"low","/favoritos"],
  ["l02","Capítulo tranquilo","Continue um livro sem meta de velocidade.",["books","rest"],["calm","neutral","tired"],30,["evening","weekend"],"low","/favoritos"],
  ["l03","Poema breve","Leia um poema ou texto curto que já possui.",["books","creativity","quick"],["sad","calm","confused"],5,["all"],"low","/favoritos"],
  ["l04","Trecho favorito","Reencontre um trecho que marcou você.",["books","favorites"],["sad","happy","calm"],10,["all"],"low","/favoritos"],
  ["l05","Leitura ao ar livre","Leve algumas páginas para um lugar seguro.",["books","outdoors","rest"],["calm","neutral"],30,["weekend","afternoon"],"low","/favoritos"],
  ["l06","Anotar uma frase","Guarde no Diário uma frase da leitura.",["books","diary"],["excited","calm","neutral"],10,["all"],"low","/diario"],
  ["l07","Escolher a próxima leitura","Veja seus livros salvos e escolha sem começar.",["books","organization","favorites"],["confused","neutral"],10,["evening"],"low","/favoritos"],
  ["l08","Ler com alguém","Compartilhe um trecho com uma pessoa próxima.",["books","social"],["happy","excited","neutral"],15,["weekend"],"low","/favoritos"],
  ["q01","Guardar uma coisa","Coloque um objeto no lugar certo.",["quick","organization"],["unmotivated","confused","neutral"],2,["all"],"low","/lar"],
  ["q02","Abrir a janela","Renove o ar se isso for seguro.",["quick","selfcare","outdoors"],["tired","neutral"],2,["morning","afternoon"],"low","/lar"],
  ["q03","Anotar um lembrete","Registre algo que não quer carregar na cabeça.",["quick","calendar","organization"],["anxious","confused"],2,["all"],"low","/calendario"],
  ["q04","Escolher uma música","Separe uma faixa para ouvir mais tarde.",["quick","music"],["neutral","happy"],2,["all"],"low","/lar"],
  ["q05","Apagar uma notificação","Limpe somente um aviso que não precisa ficar.",["quick","organization"],["confused","irritated"],2,["all"],"low","/lar"],
  ["q06","Agradecer o corpo","Perceba uma parte do corpo que sustentou seu dia.",["quick","selfcare"],["tired","sad","neutral"],2,["night"],"low","/lar"],
  ["q07","Registrar o humor","Escolha como se sente, ou prefira não dizer.",["quick","diary"],["neutral","confused","anxious"],2,["all"],"low","/lar"],
  ["i01","Começo sem notificações","Passe os primeiros minutos do dia com calma.",["starting","rest"],["neutral","anxious","tired"],10,["morning"],"low","/lar"],
  ["i02","Abrir as cortinas","Deixe a luz entrar quando for confortável.",["starting","outdoors","quick"],["tired","calm","neutral"],2,["morning"],"low","/lar"],
  ["i03","Plano de uma linha","Defina em uma frase o essencial de hoje.",["starting","organization","diary"],["confused","anxious","neutral"],5,["morning"],"low","/diario"],
  ["i04","Noite preparada","Separe uma coisa que facilitará amanhã.",["closing","organization"],["tired","neutral"],5,["night"],"low","/lar"],
  ["i05","Tela mais tranquila","Reduza brilho e estímulos antes de descansar.",["closing","rest","selfcare"],["tired","anxious","irritated"],10,["night"],"low","/lar"],
  ["i06","Fechar o calendário","Confira amanhã uma vez e encerre o planejamento.",["closing","calendar"],["anxious","confused"],5,["night"],"low","/calendario"],
  ["i07","Ritual de encerramento","Guarde objetos usados e escolha uma música calma.",["closing","music","organization"],["neutral","tired"],15,["evening","night"],"low","/lar"],
  ["i08","Madrugada sem cobrança","Se ainda estiver acordado, escolha apenas descansar.",["closing","rest","selfcare"],["tired","anxious","sad"],15,["night"],"low","/lar"],
  ["x01","Quebra-cabeça breve","Faça uma pequena atividade de lógica.",["distraction","creativity","quick"],["confused","irritated","neutral"],10,["all"],"low","/lar"],
  ["x02","Rever fotos escolhidas","Olhe poucas fotos que você gosta.",["distraction","favorites","rest"],["sad","calm","neutral"],10,["all"],"low","/favoritos"],
  ["x03","Dobradura simples","Crie algo pequeno com papel disponível.",["distraction","creativity"],["anxious","confused","neutral"],15,["all"],"low","/lar"],
  ["x04","Palavras por letra","Liste palavras que começam com a mesma letra.",["distraction","creativity","quick"],["confused","neutral"],5,["all"],"low","/lar"],
  ["x05","Organizar uma playlist","Agrupe algumas músicas por momento.",["distraction","music","organization"],["excited","calm","neutral"],15,["weekend","evening"],"low","/lar"],
  ["x06","Receita para outro dia","Salve uma ideia de receita sem precisar fazê-la.",["distraction","favorites","organization"],["tired","neutral"],5,["all"],"low","/favoritos"],
  ["x07","Jogo com companhia","Escolha um jogo curto com alguém próximo.",["distraction","social"],["happy","excited","neutral"],30,["weekend","evening"],"medium","/lar"],
];

export const COMPANION_CATALOG = Object.freeze(rows.map((row) => Object.freeze({
  id: row[0], title: row[1], description: row[2], categories: row[3],
  moods: row[4], minutes: row[5], periods: row[6], energy: row[7],
  route: row[8], reason: "Combina com o momento e os filtros escolhidos.",
})));

export const COMPANION_CATEGORIES = Object.freeze([
  "rest","selfcare","organization","creativity","movement","outdoors","social",
  "diary","goals","habits","music","screen","books","quick","starting","closing",
  "distraction",
]);
